title: Aevatar Weekly Decks
description: Weekly progress presentations for the Aevatar team
url: ""
baseurl: "/aevatar-deck"

collections:
  decks:
    output: true
    sort_by: date

defaults:
  - scope:
      path: ""
      type: "decks"
    values:
      layout: "deck"
      author: "Aevatar Team"

team_members:
  - Shining
  - Ean
  - Louis
  - Potter
  - Haylee
  - Kai Wei
  - Kai Huei

future: true

exclude:
  - vendor
  - .bundle

plugins:
  - jekyll-seo-tag
